# Generated by Django 3.1 on 2020-10-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Conten_head0',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='post',
            name='Content_head1',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='post',
            name='Content_head2',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
